### ISSUE TITLE
Version 2.8.1 does not display any video content when using LibVA with an Intel Arc GPU.

### ISSUE THREAD

**Issue by lavadrop** [flathub/org.avidemux.Avidemux#17]
No video, just a blank field when using LibVA. Sound is unaffected.
I'm using an Intel Arc A380 GPU.
Mesa 23.1.3

**Comment by ell1e** [comment]
Seems to affect basic regular intel integrated GPUs like Skylake too. Or at least it looks the same on such a machine, and actually no matter what video output setting I pick it will never display anything:

[avidemux_video_output_demo.webm](https://github.com/flathub/org.avidemux.Avidemux/assets/64124388/1b07c82e-2566-4021-9621-e23ea1b1c117)

**Comment by guihkx** [comment]
Is this still a problem? I'm unable to test it, as I don't have an Intel GPU.

**Comment by HugLifeTiZ** [comment]
It's not happening for me in Plasma 5.27. My laptop is a hybrid with an Intel iGPU and a Nvidia GTX 2060 dGPU, and it uses offloading. Which means the iGPU is responsible for handling video rendering.

I looked around for an upstream bug tracker and couldn't find one. I guess this one is the best we've got! ...Which is what I was **about** to say, until I found [an organization improvement PR](https://github.com/mean00/avidemux2/pull/507) from December in the github repo we pull from, which creates an [organization.md file](https://github.com/mean00/avidemux2/blob/08b87123823d48ee7b916987151e8d76117ed5ed/organization.md) that links to [the *actual* issue tracker on SourceForge.](https://sourceforge.net/p/avidemux/_list/tickets) So if system package versions of Avidemux are still exhibiting this issue, and you want to slog through whatever it takes to file issues on SourceForge, go ahead.

@guihkx, since you and I are likely now the main maintainers of this package, we may want to lend our support to that PR.

**Comment by guihkx** [comment]
>It's not happening for me in Plasma 5.27. My laptop is a hybrid with an Intel iGPU and a Nvidia GTX 2060 dGPU, and it uses offloading. Which means the iGPU is responsible for handling video rendering.

That's promising, thank you for testing. But I think we should wait for an additional confirmation from either @lavadrop or @ell1e.

> [the _actual_ issue tracker on SourceForge](https://sourceforge.net/p/avidemux/_list/tickets)

Nice, thanks for the link, I didn't know one existed, either. Although, to be honest, it doesn't seem like anyone has been looking over those tickets for years. :/

> So if system package versions of Avidemux are still exhibiting this issue, and you want to slog through whatever it takes to file issues on SourceForge, go ahead.

Nah, to me the Flatpak package being fixed is good enough to close this.

> @guihkx, since you and I are likely now the main maintainers of this package, we may want to lend our support to that PR.

I see your point, but I don't think this is an official package of Avidemux..? Or am I wrong?

**Comment by HugLifeTiZ** [comment]
> I see your point, but I don't think this is an official package of Avidemux..? Or am I wrong?

No, it's not. The maintainers of the repo we pull from are not involved in this packaging, and I'm not making commits to that repo. I don't think you are, either. So by that metric, this is not an "official" package. Yet we are packaging it, and it's the easiest way to install it on many distros. So the fact that we are packaging it means something, but exactly how much that means should be determined by the upstream maintainers evaluating the proposal.

**Comment by guihkx** [comment]
Thanks for the clarification. Let's please continue this discussion in #25.

**Comment by lavadrop** [comment]
> Is this still a problem? I'm unable to test it, as I don't have an Intel GPU.

Yes, it still is a problem, all other backends work, LibVA does not. I am using Intel Arc, though.

**Comment by guihkx** [comment]
Thanks. Can you please test with the official AppImage, too?

If this issue happens with the official package, I don't think there's much we can (or should) do here.

**Comment by lavadrop** [comment]
Main branch has same bug. Closing.
